version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  mongo-data:
